keramika_ostrovni_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('keramika_ostrovni_web.urls')),
]

keramika_ostrovni_web/urls.py
from django.urls import path
from keramika_ostrovni_web import views

urlpatterns = [
    path("", views.index, name="index"),
    path("deti", views.children, name="children"),
    path("zapis-krouzku", views.provizorni_zapis, name="provizorni_zapis"),
    path("dospeli", views.adults, name="adults"),
    path("lektori", views.teachers, name="teachers"),

    path("account-signup", views.provizorni_zapis, name="children_sign_up"),
    path("account-login", views.provizorni_zapis, name="children_login"),
    path("account-logout", views.provizorni_zapis, name="children_logout"),
    path("account-info", views.provizorni_zapis, name="account_info"),
    path("account-info-edit", views.provizorni_zapis, name="account_info_edit"),
    path("dite-edit/<int:child_id>", views.provizorni_zapis, name="child_edit"),
    path("dite-nove", views.provizorni_zapis, name="child_add_new"),
    path("zapis-krouzku", views.provizorni_zapis, name="children_sign_into_classes"),
    path("zapis-krouzku/zapsano", views.provizorni_zapis, name="sign_up_child"),
    path("dospely-edit/<int:adult_id>", views.provizorni_zapis, name="adult_edit"),
    path("dospely-novy", views.provizorni_zapis, name="adult_add_new"),
    #path("account-signup", views.children_sign_up, name="children_sign_up"),
    #path("account-login", views.children_login, name="children_login"),
    #path("account-logout", views.children_logout, name="children_logout"),
    #path("account-info", views.account_info, name="account_info"),
    #path("account-info-edit", views.account_info_edit, name="account_info_edit"),
    #path("dite-edit/<int:child_id>", views.child_edit, name="child_edit"),
    #path("dite-nove", views.child_add_new, name="child_add_new"),
    #path("zapis-krouzku", views.children_sign_into_classes, name="children_sign_into_classes"),
    #path("zapis-krouzku/zapsano", views.sign_up_child, name="sign_up_child"),
    # path("dospely-edit/<int:adult_id>", views.adult_edit, name="adult_edit"),
    # path("dospely-novy", views.adult_add_new, name="adult_add_new"),
]

keramika_ostrovni_web/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User


# Create your models here.


class Aktuality(models.Model):
    TYPE_CHOICES = (('adults', 'dospeli'), ('children', 'deti'))
    COLOR_CHOICES = (('black', 'černá'), ('crimson', 'červená'), ('darkblue', 'modrá'))
    text_zpravy_cs = models.CharField(max_length=1000, blank=False)
    text_zpravy_en = models.CharField(max_length=1000, default='Sorry, no translation available yet')
    barva_textu = models.CharField(max_length=16, choices=COLOR_CHOICES, default='black')
    datum = models.DateField(auto_now=True)
    typ_aktualit = models.CharField(max_length=16, choices=TYPE_CHOICES, default='children')


class Krouzek(models.Model):
    DAY_CHOICES = (
        ('mon', 'pondělí'), ('tue', 'úterý'), ('wed', 'středa'), ('thu', 'čtvrtek'), ('fri', 'pátek'),
        ('sat', 'sobota'),
        ('sun', 'neděle'))
    cislo_krouzku = models.IntegerField(default=100)
    den = models.CharField(max_length=16, choices=DAY_CHOICES, default='mon')
    od = models.CharField(max_length=5, default='00:00')
    do = models.CharField(max_length=5, default='00:00')
    zaci_trida = models.CharField(max_length=20, default='1-2')
    ucitel = models.CharField(max_length=30, default='Eva Lukášová')
    max_kapacita_krouzku = models.IntegerField(default=10)
    cena = models.IntegerField(default=2000)

    start_fronty = models.IntegerField(default=0)
    konec_fronty = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.cislo_krouzku}:{self.den} {self.od}-{self.do}; fronta({self.start_fronty},{self.konec_fronty})"


class LekceDospeli(models.Model):
    DAY_CHOICES = (
        ('mon', 'pondělí'), ('tue', 'úterý'), ('wed', 'středa'), ('thu', 'čtvrtek'), ('fri', 'pátek'),
        ('sat', 'sobota'),
        ('sun', 'neděle'))
    cislo_krouzku = models.IntegerField(default=9000)
    den = models.CharField(max_length=16, choices=DAY_CHOICES, default='thu')
    datum = models.DateField()
    od = models.CharField(max_length=5, default='16:00')
    do = models.CharField(max_length=5, default='19:00')
    ucitel = models.CharField(max_length=30, default='Eva Lukášová')
    max_kapacita_krouzku = models.IntegerField(default=10)
    cena = models.IntegerField(default=100)


class Dite(models.Model):
    username = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="deti"
    )
    jmeno = models.CharField(max_length=20, blank=False)
    prijmeni = models.CharField(max_length=20, blank=False)
    # 3.A
    rocnik = models.IntegerField(blank=False)
    paralelka = models.CharField(max_length=1, blank=False)
    # 2020/2021
    ve_skolnim_roce = models.CharField(max_length=9, blank=False)

    zapsany_krouzek = models.ManyToManyField(Krouzek, blank=True, related_name='zaci_krouzku')
    zapsany_JN_krouzek = models.ManyToManyField(Krouzek, blank=True,
                                                related_name='nahradnici_krouzku')  # jako nahradnik
    poradi_nahradnika = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.jmeno} {self.prijmeni}, {self.rocnik}.{self.paralelka}"


"""
class FrontaNahradniku(models.Model):

    krouzek = models.ForeignKey(Krouzek,
                                on_delete=models.CASCADE,
                                related_name="fronta"
                                )
    start_fronty = models.IntegerField(max_length=9,default=0)
    konec_fronty = models.IntegerField(max_length=9,default=0)
    def __str__(self):
        return f"Fronta ke krouzku {self.krouzek}, {self.start_fronty}-{self.konec_fronty}"
"""


class Dospely(models.Model):
    username = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="dospeli"
    )
    jmeno = models.CharField(max_length=20, blank=False)
    prijmeni = models.CharField(max_length=20, blank=False)

    def __str__(self):
        return f"{self.jmeno} {self.prijmeni}"


class KontaktInfo(models.Model):
    username = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="kontakt_info"
    )
    jmeno = models.CharField(max_length=20, blank=True)
    prijmeni = models.CharField(max_length=20, blank=True)
    telefoni_cislo = models.IntegerField(null=True, blank=True, default=None)
    email = models.EmailField(max_length=254)  # ,default=User.username)

    def __str__(self):
        return f"{self.jmeno} {self.prijmeni} {self.telefoni_cislo} {self.email}"


class PlatebniInfo(models.Model):
    username = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="platebni_info"
    )
    cislo_uctu = models.CharField(max_length=50, default="0800/7625489755")
    var_symbol = models.IntegerField(default=120)
    suma_k_zaplaceni = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.cislo_uctu} {self.var_symbol}  {self.suma_k_zaplaceni}kc"

keramika_ostrovni_web/views.py
from django.shortcuts import render, Http404, HttpResponseRedirect, HttpResponse, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from .models import Aktuality, Dite, Dospely, Krouzek, KontaktInfo, PlatebniInfo, LekceDospeli
from .forms import DiteForm, DospelyForm, KontaktInfoForm
from django.urls import reverse

# Create your views here.
def index(request):
    # return HttpResponse("hello there")
    print(request.user.username)
    context = {
        "username": request.user.username
    }
    return render(request, "keramika_ostrovni_web/index.html", context)


def children(request):
    context = {
        "username": request.user.username,
        "aktuality": Aktuality.objects.filter(typ_aktualit='children').all().order_by("-datum"),
        "courses": Krouzek.objects.all().order_by("cislo_krouzku")
    }

    for course in context.get('courses'):
        course.den_cs, course.den_en = day_to_text_dict(course.den)
        #print(course.den)
        #print(course.den_cs)
        #print(course.den_en)
        #print("...............")

    # for course in context.get('courses'):
    #     children = course.zaci_krouzku.all()
    #     print(children)

    return render(request, "keramika_ostrovni_web/children.html", context)

def provizorni_zapis(request):
    context = {
        "courses": Krouzek.objects.all().order_by("cislo_krouzku")
    }
    poradove_cislo=0
    links = [
        "http://www.branajazyku.cz/keramika-1-ostrovni",
        "http://www.branajazyku.cz/keramika-2-ostrovni",
        "http://www.branajazyku.cz/keramika-3-ostrovni",
        "http://www.branajazyku.cz/keramika-4-ostrovni-0",
        "http://www.branajazyku.cz/keramika-5-ostrovni"]
    for course in context.get('courses'):
        course.den_cs, course.den_en = day_to_text_dict(course.den)
        course.link = links[poradove_cislo]
        poradove_cislo = poradove_cislo + 1
        course.poradi=poradove_cislo



    return render(request, "keramika_ostrovni_web/provizorni_zapis.html", context)

def day_to_text_dict(course_day):
    course_day_cs = ""
    course_day_en = ""
    if course_day == "mon":
        course_day_cs = "pondělí"
        course_day_en = "monday"
    if course_day == "tue":
        course_day_cs = "úterý"
        course_day_en = "tuesday"
    if course_day == "wed":
        course_day_cs = "středa"
        course_day_en = "wednesday"
    if course_day == "thu":
        course_day_cs = "čtvrtek"
        course_day_en = "thursday"
    if course_day == "fri":
        course_day_cs = "pátek"
        course_day_en = "friday"
    if course_day == "sat":
        course_day_cs = "sobota"
        course_day_en = "saturday"
    if course_day == "sun":
        course_day_cs = "neděle"
        course_day_en = "sunday"

    return course_day_cs, course_day_en


def children_sign_up(request):
    context = {"username": request.user.username}
    print(request.method)
    if request.method == 'POST':
        form = UserCreationForm(request.POST)  # data validation
        if form.is_valid():
            user = form.save()  # saves data to db
            login(request, user)
            return redirect('children')
        else:
            return render(request, "keramika_ostrovni_web/children_sign_up.html",
                          {"username": request.user.username, 'form': form})

    if request.method == 'GET':
        form = UserCreationForm()  # create blank instance of the form and send it to the user
        context = {"username": request.user.username, 'form': form}
    return render(request, "keramika_ostrovni_web/children_sign_up.html", context)


def children_login(request):
    context = {"username": request.user.username}
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)  # data validation
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('children')
        else:
            return render(request, "keramika_ostrovni_web/children_login.html",
                          {"username": request.user.username, 'form': form})

    if request.method == 'GET':
        form = AuthenticationForm()  # create blank instance of the form and send it to the user
        context = {"username": request.user.username, 'form': form}
    return render(request, "keramika_ostrovni_web/children_login.html", context)


def account_info(request):
    print("+++++----+++++")
    if request.user.is_anonymous:
        print("is anonym")
        raise Http404("Prosíme, nejprve se přihlašte :)")
    print(request)
    if request.method == 'GET':
        username = request.user.username

        children = request.user.deti.all()
        form = DiteForm()  # create blank instance of the form and send it to the user

        adults = request.user.dospeli.all()
        contact_info = request.user.kontakt_info.all()  # todo clean code
        payment_info = request.user.platebni_info.all()
        if len(contact_info) > 0:
            contact_info = contact_info[0]
        if len(payment_info) > 0:
            payment_info = payment_info[0]
        print(contact_info)
        print(payment_info)

        context = {"username": username, 'form': form, "children": children, "dospeli": adults,
                   "platebni_info": payment_info, "kontakt_info": contact_info}
    return render(request, "keramika_ostrovni_web/account_info.html", context)


def account_info_edit(request):
    if request.user.is_anonymous:
        print("is anonym")
        raise Http404("Prosíme, nejprve se přihlašte :)")
    username = request.user.username
    try:
        print(request.user.kontakt_info.all())
        contact_info = request.user.kontakt_info.all()[0]  # todo make it nicer
        payment_info = request.user.platebni_info.all()[0]
    except KontaktInfo.DoesNotExist or PlatebniInfo.DoesNotExist:
        raise Http404("KontaktInfo or PlatebniInfo does not exist, sorries")
    except IndexError:
        contact_info = KontaktInfo(username=request.user)
        contact_info.save()
        payment_info = PlatebniInfo(username=request.user)
        payment_info.save()

    if request.method == 'GET':
        form_contact = KontaktInfoForm()
        if len(contact_info.email) == 0:  # if empty email assume username is email
            try:
                contact_info.email = username
                contact_info.save()
            except:
                print("not valid email really...")
        context = {"username": username, 'form_contact': form_contact, 'contact_info': contact_info,
                   'payment_info': payment_info}
        return render(request, "keramika_ostrovni_web/account_info_edit.html", context)
    if request.method == 'POST':
        form_contact = KontaktInfoForm(data=request.POST)  # data validation
        if ((request.POST.get('input_button', "") == "Uložit změny") or (
                request.POST.get('input_button', "") == "Save changes")):
            if form_contact.is_valid():

                contact_info.jmeno = request.POST.get('jmeno', "")
                contact_info.prijmeni = request.POST.get('prijmeni', "")
                contact_info.telefoni_cislo = request.POST.get('telefoni_cislo', "")
                contact_info.email = request.POST.get('email', "")
                contact_info.save()
                return redirect('account_info')
            else:
                print("form not valid")
                print(form_contact.error_messages)
                context = {"username": username, 'form_contact': form_contact, 'contact_info': contact_info,
                           'payment_info': payment_info}
                return render(request, "keramika_ostrovni_web/account_info_edit.html", context)

        if (request.POST.get('input_button', "") == "Storno"):
            return redirect('account_info')


def child_edit(request, child_id):
    if request.user.is_anonymous:
        print("is anonym")
        raise Http404("Prosíme, nejprve se přihlašte :)")
    username = request.user.username
    try:
        user_children = request.user.deti.all()
        print(user_children)
        child = user_children.get(pk=child_id)
    except Dite.DoesNotExist:
        raise Http404("Dite does not exist, sorries")

    if request.method == 'GET':
        form = DiteForm()
        context = {"username": username, 'form': form, "child": child}
        return render(request, "keramika_ostrovni_web/child_edit.html", context)
    if request.method == 'POST':
        form = DiteForm(data=request.POST)  # data validation
        if ((request.POST.get('input_button', "") == "Uložit změny") or (
                request.POST.get('input_button', "") == "Save changes")):
            if form.is_valid():
                print(child)
                child.jmeno = request.POST.get('jmeno', "")
                child.prijmeni = request.POST.get('prijmeni', "")
                child.rocnik = request.POST.get('rocnik', "")
                child.paralelka = request.POST.get('paralelka', "")
                child.ve_skolnim_roce = request.POST.get('ve_skolnim_roce', "")
                print("new")
                print(child)
                child.save()
                #print(Dite.objects.all())
                return redirect('account_info')
            else:
                print("form not valid")
                print(form.error_messages)
                return render(request, "keramika_ostrovni_web/child_edit.html",
                              {"username": username, 'form': form, "child": child})
        if (request.POST.get('input_button', "") == "Storno"):
            return redirect('account_info')
        if ((request.POST.get('input_button', "") == "Smazat záznam") or (
                request.POST.get('input_button', "") == "Delete entry")):
            child.delete()
            return redirect('account_info')

keramika_ostrovni_web/templates/keramika_ostrovni_web/account_info_edit.html
{% extends "keramika_ostrovni_web/edit_form_base.html" %}
{% block form %}
     <form class="site-form" action="{% url 'account_info_edit' %}" metdod="post" style="margin: 5vh 0% 5vh 0%;">
        {% csrf_token %}

        <div id="info-table" class="grid-container">
            <div id="form-outside">
                <div id="forminsides" class="row">
                    <div class="col-md-12">
                        <div class="info-inner-div">
                                <div style="margin-top: 10px">
                                <label >{{ username }}</label>
                                <hr>
                            </div>
                            <div>
                                <label  class="cs-lang" for="id_jmeno">Jméno:</label>
                                <label  class="en-lang" for="id_jmeno">Name:</label>
                            </div>
                            <div>
                                <input type="text" name="jmeno" maxlength="20" id="id_jmeno"
                                       value="{{ contact_info.jmeno }}">
                            </div>
                            <div>
                                <label  class="cs-lang" for="id_prijmeni">Příjmení:</label>
                                  <label  class="en-lang" for="id_prijmeni">Surname:</label>
                            </div>
                            <div>
                               <input type="text" name="prijmeni" maxlength="20" id="id_prijmeni"
                                       value="{{ contact_info.prijmeni }}">
                            </div>

                            <div>
                                <label  class="cs-lang" for="id_telefoni_cislo">Tel. číslo:</label>
                                 <label  class="en-lang" for="id_telefoni_cislo">Phone number:</label>
                            </div>
                            <div>
                               <input type="number" name="telefoni_cislo" id="id_telefoni_cislo"
                                       value="{{ contact_info.telefoni_cislo }}">
                            </div>

                              <div>
                                <label  for="id_email">Email</label>
                            </div>
                            <div  style="margin-bottom: 10px">
                              <input type="email" name="email" maxlength="254" required id="id_email"
                                       value="{{ contact_info.email }}">
                            </div>
                        </div>
                    </div>

                </div>
                <div id="form-buttons" class="row">
                    <div class="col-lg-6">
                        <div class="row">
                            <div class="mx-auto co-12 button-inner-div">
                               <input name="input_button" class="cs-lang change-button" type="submit" formmethod="post"
                               value="Storno"></input>
                        <input name="input_button" class="en-lang change-button" type="submit" formmethod="post"
                               value="Storno"></input>
                            </div>
                        </div>

                    </div>
                    <div class="col-lg-6">
                        <div class="row">
                            <div class="mx-auto co-12 button-inner-div">
                          <input name="input_button" class="cs-lang change-button" type="submit" formmethod="post"
                               value="Uložit změny"></input>
                        <input name="input_button" class="en-lang change-button" type="submit" formmethod="post"
                               value="Save changes"></input>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </form>
{% endblock %}

keramika_ostrovni_web/templates/keramika_ostrovni_web/basetemplate.html
{% extends "keramika_ostrovni_web/base.html" %}
{% block title %}Keramická dílna brána jazyků{% endblock %}
{% block links %}
    <link rel="stylesheet" href="../../static/keramika_ostrovni_web/css/children_styling.css">{% endblock %}
{% block js %}

{% endblock %}
{% block page_content %}

{% endblock %}

keramika_ostrovni_web/templates/keramika_ostrovni_web/child_edit.html
{% extends "keramika_ostrovni_web/edit_form_base.html" %}
{% block form %}
    <form class="site-form" action="{% url 'child_edit'  child_id=child.id %}" metdod="post"
          style="margin: 5vh 0% 5vh 0%;">
        {% csrf_token %}

        <div id="info-table" class="grid-container">
            <div id="form-outside">
                <div id="forminsides" class="row">
                    <div class="col-md-12">
                        <div class="info-inner-div">
                            <div>
                                <label  class="cs-lang" for="id_jmeno">Jméno:</label>
                                <label  class="en-lang" for="id_jmeno">Name:</label>
                            </div>
                            <div>
                                <input type="text" name="jmeno" maxlength="20" required id="id_jmeno"
                                       value="{{ child.jmeno }}">
                            </div>
                            <div>
                                <label  class="cs-lang" for="id_prijmeni">Příjmení:</label>
                                  <label  class="en-lang" for="id_prijmeni">Surname:</label>
                            </div>
                            <div>
                                <input type="text" name="prijmeni" maxlength="20" required id="id_prijmeni"
                                       value="{{ child.prijmeni }}">
                            </div>
                            <div>
                                <label class="cs-lang" for="id_rocnik">Třída:</label>
                                <label class="en-lang" for="id_rocnik">Class:</label>
                            </div>
                            <div class="row">
                                <div class="col-2">
                                    <input type="number" name="rocnik" style=" width: 60px;" required id="id_rocnik"
                                           value="{{ child.rocnik }}"/>
                                </div>
                                <div class="col-2">
                                    <input type="text" name="paralelka" size="1" maxlength="1" required
                                           id="id_paralelka"
                                           value="{{ child.paralelka }}"/>
                                </div>
                            </div>
                            <div>
                                <label  class="cs-lang" for="id_ve_skolnim_roce">Ve školním roce:</label>
                                 <label  class="en-lang" for="id_ve_skolnim_roce">School year:</label>
                            </div>
                            <div>
                                <input type="text" name="ve_skolnim_roce" maxlength="9" required
                                       id="id_ve_skolnim_roce" value="{{ child.ve_skolnim_roce }}">
                            </div>
                        </div>
                    </div>

                </div>
                <div id="form-buttons" class="row">
                    <div class="col-lg-4">
                        <div class="row">
                            <div class="mx-auto co-12 button-inner-div">
                                <input name="input_button" class="cs-lang change-button" type="submit" formmethod="post"
                                       value="Uložit změny"></input>
                                <input name="input_button" class="en-lang change-button" type="submit" formmethod="post"
                                       value="Save changes"></input>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="row">
                            <div class="mx-auto co-12 button-inner-div">
                                <input name="input_button" class="cs-lang change-button" type="submit" formmethod="post"
                                       value="Storno"></input>
                                <input name="input_button" class="en-lang change-button" type="submit" formmethod="post"
                                       value="Storno"></input>
                            </div>
                        </div>

                    </div>
                    <div class="col-lg-4">
                        <div class="row">
                            <div class="mx-auto co-12 button-inner-div">
                                <input name="input_button" class="cs-lang change-button" type="submit" formmethod="post"
                                       value="Smazat záznam"></input>
                                <input name="input_button" class="en-lang change-button" type="submit" formmethod="post"
                                       value="Delete entry"></input>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </form>
{% endblock %}

keramika_ostrovni_web/templates/keramika_ostrovni_web/children_add_new.html
{% extends "keramika_ostrovni_web/edit_form_base.html" %}
{% block form %}
    <form class="site-form" action="{% url 'child_add_new' %}" metdod="post" style="margin: 5vh 0% 5vh 0%;">
        {% csrf_token %}

        <div id="info-table" class="grid-container">
            <div id="form-outside">
                <div id="forminsides" class="row">
                    <div class="col-md-12">
                        <div class="info-inner-div">
                            <div>
                                <label  class="cs-lang" for="id_jmeno">Jméno:</label>
                                <label  class="en-lang" for="id_jmeno">Name:</label>
                            </div>
                            <div>
                                <input type="text" name="jmeno" maxlength="20" required id="id_jmeno"
                                       value="Jméno">
                            </div>
                            <div>
                                <label  class="cs-lang" for="id_prijmeni">Příjmení:</label>
                                  <label  class="en-lang" for="id_prijmeni">Surname:</label>
                            </div>
                            <div>
                                <input type="text" name="prijmeni" maxlength="20" required id="id_prijmeni"
                                       value="Příjmení">
                            </div>
                            <div>
                                <label class="cs-lang" for="id_rocnik">Třída:</label>
                                <label class="en-lang" for="id_rocnik">Class:</label>
                            </div>
                            <div class="row">
                                <div class="col-2">
                                    <input type="number" name="rocnik" style=" width: 60px;" required id="id_rocnik"
                                           value="1"/>
                                </div>
                                <div class="col-2">
                                    <input type="text" name="paralelka" size="1" maxlength="1" required
                                           id="id_paralelka"
                                           value="A"/>
                                </div>
                            </div>
                            <div>
                                <label  class="cs-lang" for="id_ve_skolnim_roce">Ve školním roce:</label>
                                 <label  class="en-lang" for="id_ve_skolnim_roce">School year:</label>
                            </div>
                            <div>
                                <input type="text" name="ve_skolnim_roce" maxlength="9" required
                                       id="id_ve_skolnim_roce" value="2021/2022">
                            </div>
                        </div>
                    </div>

                </div>
                <div id="form-buttons" class="row">
                    <div class="col-lg-6">
                        <div class="row">
                            <div class="mx-auto co-12 button-inner-div">
                                <input name="input_button" class="cs-lang change-button" type="submit" formmethod="post"
                                       value="Storno"></input>
                                <input name="input_button" class="en-lang change-button" type="submit" formmethod="post"
                                       value="Storno"></input>
                            </div>
                        </div>

                    </div>
                    <div class="col-lg-6">
                        <div class="row">
                            <div class="mx-auto co-12 button-inner-div">
                     <input name="input_button" class="cs-lang change-button" type="submit" formmethod="post" value="Uložit"></input>
                                <input name="input_button" class="en-lang change-button" type="submit" formmethod="post" value="Save"></input>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </form>
{% endblock %}